[package]
name = "vectors_of_different_objects"
version = "0.1.0"
authors = ["Aðalsteinn Rúnarsson <alli@allir.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
